### PR TITLE
Using an xml configuration file for the example project.

### PR DESCRIPTION
**Pull request by lploumen**
This way, credentials aren't included in the library.
Could be useful when library is shipped as a nuget package for example.

I had to make the class ApiAccessKeysImpl public. I'm not so sure this class should stay in the library as it is a simple interface implementation. It could be declared outside the library.

### CODE REVIEW

**Comment by krzema12** [comment]
Could you include an example GeocachingToolboxSettings.xml file, with some dummy credentials, so that it's easier for the developers to onboard?

**Review by krzema12 — COMMENTED** [review]
Hmm, it's weird. Why GitHub shows that the files were replaced if there are virtually no changes? Can you see it, too, in the diff? It's visible here: https://github.com/krzema12/GeocachingToolbox/pull/25/commits/d58740234e15ea8db145cf010f0bb67d3fcad294

**Comment by lploumen** [comment]
Actually, I copied all the files from the /lploumen/GeocacheLocator2/GeocachingToolBox to /lploumen/GeocachingToolbox because the latest version is in /lploumen/GeocacheLocator2/GeocachingToolBox.
As I wanted the library to live on its own, it's better to have its own repository and that the app references it (via git submodules as I read this morning).
That's probably why Github shows that the files were replaced.
Also glad to hear from you, it's been a long time :)

**Comment by krzema12** [comment]
Ok, makes sense.
Nice to hear from you, too :) As I don't have much time for this project now, I propose two paths: either please continue the project on your own, or send me pull requests as a bigger group of small commits (let's say, 10 commits at most). What do you think?
I may get back to the project one day, though.

**Comment by krzema12** [comment]
Also, please remember to resolve all related issues in the bug tracker :)

**Comment by lploumen** [comment]
Pay also attention that my fork is heavily modified to suit my needs, it was not really intended to be merged a this point...
Anyway, if I do changes, I'll send PR as small commits, it's always better.

**Comment by krzema12** [comment]
To be honest, I don't have much time to go really deep into your changes (especially if they span multiple commits), so I kinda trust you :) I'll try to do some sanity reviews, though, so no worries.

**Pull request merged**
